#ifndef _NEW_FS_UPDATE_H_
#define _NEW_FS_UPDATE_H_
#include "typedef.h"

enum {
    UPDATE_ERR_NONE = 0,
    UPDATE_ERR_UFW_HEAD_CRC_ERR,
    UPDATE_ERR_NOT_FIND_LOADER_FILE,
    UPDATE_ERR_NOT_FIND_TARGET_LOADER,

    UPDATE_ERR_LOADER_HEAD_CRC_ERR = 4,
    UPDATE_ERR_MALLOC_ERR,
    UPDATE_ERR_LOADER_WRITE_ERR,
    UPDATE_ERR_FILE_HANDLE_ERR,

    UPDATE_ERR_LOADER_VERIFY_ERR = 8,
    UPDATE_ERR_NOT_FIND_FLASH_BIN,
    UPDATE_ERR_FLASH_HEAD_CRC_ERR,
    UPDATE_ERR_NOT_FIND_TARGET_FILE,

    UPDATE_ERR_KEY_ERR = 12,
    UPDATE_ERR_UBOOT_NOT_MATCH,
    UPDATE_ERR_READ_REMOTE_FILE_ERR,
    UPDATE_ERR_REMOTE_RES_FILE_CRC_ERR,

    UPDATE_ERR_CODE_VERIFY_ERR = 16,
    UPDATE_ERR_RES0_VERIFY_ERR,
    UPDATE_ERR_NOT_FIND_RESERVE_DIR_FILE,
    UPDATE_ERR_LOCAL_FILE_HEAD_CRC_ERR,

    UPDATE_ERR_LOCAL_FILE_DATA_CRC_ERR = 20,
    UPDATE_ERR_PARAM_ERR,
    UPDATE_ERR_BT_CFG_UPDATE_ERR,
    UPDATE_ERR_TONE_UPDATE_ERR,

    UPDATE_ERR_RESERVED_CONFIG_UPDATE_ERR = 24,
    UPDATE_ERR_PRODUCT_ID_NOT_MATCH,
    UPDATE_ERR_EX_DSP_UPDATE_ERR,
    UPDATE_ERR_CONN_ERR,

    UPDATE_ERR_ERASE_FAIL = 28,
    UPDATE_ERR_UPDATE_FILE_SIZE_ERR,
    UPDATE_ERR_ANC_CFG_UPDATE_ERR,
    UPDATE_ERR_ANC_COEF_UPDATE_ERR,

    UPDATE_ERR_RESERVED_ZONE_UPDATE_ERR = 32,

    UPDATE_ERR_BR40_FLASH_ID_ERR,
    UPDATE_ERR_BR40_CHIP_ID_ERR,
    UPDATE_ERR_BR40_EFUSE_OVERWRITE_ERR,
    UPDATE_ERR_BR40_EFUSE_BT_NAME_ERR,
    UPDATE_ERR_BR40_EFUSE_CHANNEL_ERR,
    UPDATE_ERR_BR40_ISD_CONFIG_ERR,
    UPDATE_ERR_LOCAL_EFUSE_CRC_ERR,
    UPDATE_ERR_LOCAL_EFUSE_WRITE_ERR,
    UPDATE_ERR_BR40_WRITE_P11_CODE_ERR,

};

enum {
    UPDATE_PART_BT_CFG = BIT(0),
    UPDATE_PART_TONE = BIT(1),
    UPDATE_PART_RESERVED = BIT(2),
    UPDATE_PART_ANC_CFG = BIT(3),
    UPDATE_PART_ANC_COEF = BIT(4),

    UPDATE_PART_ALL_FLASH = 0xffffffff,
};

#define UPDATE_RESULT_FLAG_BITMAP	(BIT(7))
//update result code;
enum {
    UPDATE_RESULT_FILE_SIZE_ERR = 0x1, //升级文件大小错误
    UPDATE_RESULT_LOADER_SIZE_ERR = 0x2, //update loader大小错误
    UPDATE_RESULT_LOADER_VERIFY_ERR, 	//update loader校验失败
    UPDATE_RESULT_REMOTE_FILE_HEAD_ERR, //读升级文件头错误

    UPDATE_RESULT_LOCAL_FILE_HEAD_ERR = 0x5, //读flash文件头错误
    UPDATE_RESULT_NOT_FIND_TARGET_FILE_ERR, //找不到目标文件
    UPDATE_RESULT_FILE_OPERATION_ERR,		//文件操作失败
    UPDATE_RESULT_FLASH_DATA_VERIFY_ERR,    //flash数据校验失败

    UPDATE_RESULT_UBOOT_NOT_MATCH = 0x09,  //UBOOT不匹配
    UPDATE_RESULT_PRODUCT_INFO_NOT_MATCH,  //产品信息不匹配,chip_name,product_id,version
    UPDATE_RESULT_EX_DSP_UPDATE_ERR,		//外部IC升级出错;
    UPDATE_RESULT_CFG_UPDATE_ERR,			//配置升级出错

    UPDATE_RESULT_FLASH_ERASE_ERR = 0x0d,	//flash 擦失败(可能是写保护)
    UPDATE_RESULT_REMOTE_FILE_NOT_MATCH,   //升级文件不匹配
    UPDATE_RESULT_ANC_CFG_UPDATE_ERR,			//ANC配置升级出错
    UPDATE_RESULT_ANC_COEF_UPDATE_ERR,			//ANC配置升级出错

    UPDATE_RESULT_ISD_CONFIG_ERR = 0x28, 	// ini文件的REQUIRE_TARGET_FEATURE配置项有误
    UPDATE_RESULT_BR40_FLASH_ID_ERR,        // ini配置了flahs升级，但芯片没有flash
    UPDATE_RESULT_BR40_CHIP_ID_ERR,         // 该芯片不在ini的SUPPORTED_LIST配置项列表里
    UPDATE_RESULT_BR40_EFUSE_OVERWRITE_ERR, // EFUSE不可重新烧写
    UPDATE_RESULT_BR40_EFUSE_BT_NAME_ERR,   // 蓝牙名不可重写
    UPDATE_RESULT_BR40_EFUSE_CHANNEL_ERR,   // channel不可重写
    UPDATE_RESULT_LOCAL_EFUSE_CRC_ERR,      // efuse校验失败
    UPDATE_RESULT_LOCAL_EFUSE_WRITE_ERR,    // efuse写失败
    UPDATE_RESULT_BR40_WRITE_P11_CODE_ERR,


};

extern u8 ufw_head_check(u32 *update_part_flag);
extern u8 flash_bin_head_check(void);
extern u8 update_type_check(u32 *update_len);
extern u8 flash_update_process(void);
extern u8 flash_file_data_verify(void);
extern u8 flash_update_reserve_area(void);
extern u8 flash_all_data_verify(void);
extern u8 flash_parts_update_check(u32 update_part_flag);
extern void clr_update_loader_record(void);
extern u32 fs_dev_mount(u16 dev_type);
extern u32 get_ex_buffer(u8 *buffer);

#endif

